// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbjacGeQcgOBnuCQeL3q24yr62zUUM_o',
    appId: '1:421570332314:web:05271a2252d5e3c5e2c123',
    messagingSenderId: '421570332314',
    projectId: 'flutter-lab-firebase-c26b5',
    authDomain: 'flutter-lab-firebase-c26b5.firebaseapp.com',
    storageBucket: 'flutter-lab-firebase-c26b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIgKYSSTLfmBmarPJn8td7Q4zzU1WdrQY',
    appId: '1:421570332314:android:8bf652fb1ba62a57e2c123',
    messagingSenderId: '421570332314',
    projectId: 'flutter-lab-firebase-c26b5',
    storageBucket: 'flutter-lab-firebase-c26b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XVWWyLTOsEcHk_7CA9SBFx_prduY0B4',
    appId: '1:421570332314:ios:2abf5c808a3e85bfe2c123',
    messagingSenderId: '421570332314',
    projectId: 'flutter-lab-firebase-c26b5',
    storageBucket: 'flutter-lab-firebase-c26b5.appspot.com',
    iosClientId: '421570332314-qvjiski0ne7l0vbd6dl65um7c8vjptg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_XVWWyLTOsEcHk_7CA9SBFx_prduY0B4',
    appId: '1:421570332314:ios:2abf5c808a3e85bfe2c123',
    messagingSenderId: '421570332314',
    projectId: 'flutter-lab-firebase-c26b5',
    storageBucket: 'flutter-lab-firebase-c26b5.appspot.com',
    iosClientId: '421570332314-qvjiski0ne7l0vbd6dl65um7c8vjptg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabFirebas',
  );
}